---
title: "Coding"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  fig.width = 5,
  fig.asp = 0.618,
  out.width = "70%",
  dpi = 120,
  fig.align = "center",
  cache = FALSE
)
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(modelr))
diamonds <- readr::read_csv("data/sample_data.csv")
```

```{r}
diamond_1 <- diamonds %>%
  select(carat, cut, clarity, price)
```


```{r, fig.width = 8}
diamond_1 %>%
  pivot_longer(cols = cut:clarity,
               names_to = "measurement",
               values_to = "value") %>%
  ggplot() +
    geom_point(mapping = aes(x = value, y = price)) +
    facet_wrap(~ measurement, scales = "free_x")
```
```{r, fig.width = 8}
diamond_1 %>%
  ggplot() +
    geom_point(mapping = aes(x = carat, y = price))
```

```{r}
Diamond_model_a <- lm(price ~ carat, data = diamond_1)
```
```{r}
Diamond_model_a %>%
  tidy()
```
```{r}
Diamond_model_a %>%
  glance()
```
R squared is close to 1

```{r}
Diamond_model_u <- lm(price ~ cut, data = diamond_1)
```

```{r}
Diamond_model_y <- lm(price ~ clarity, data = diamond_1)
```

```{r}
Diamond_model_u %>%
  tidy()
```


```{r}
Diamond_model_y %>%
  tidy()
```

```{r}
Diamond_model_u %>%
  glance()
```



```{r}
Diamond_model_y %>%
  glance()
```

```{r}
diamond_ma_df <- diamonds %>%
  add_predictions(Diamond_model_a) %>%
  add_residuals(Diamond_model_a)
```
```{r}
diamond_ma_df
```
```{r}
ggplot(diamond_ma_df) +
  geom_point(mapping = aes(x = price, y = carat)) +
  geom_abline(slope = Diamond_model_a$coefficients[2], intercept = Diamond_model_a$coefficients[1])
```

```{r}
diamond_mu_df <- diamonds %>%
  add_predictions(Diamond_model_u) %>%
  add_residuals(Diamond_model_u)
```
```{r}
diamond_mu_df
```
```{r}
ggplot(diamond_mu_df) +
  geom_point(mapping = aes(x = price, y = cut)) +
  geom_abline(slope = Diamond_model_u$coefficients[2], intercept = Diamond_model_u$coefficients[1])
```

```{r}
diamond_my_df <- diamonds %>%
  add_predictions(Diamond_model_y) %>%
  add_residuals(Diamond_model_y)
```
```{r}
diamond_my_df
```
```{r}
ggplot(diamond_my_df) +
  geom_point(mapping = aes(x = price, y = clarity)) +
  geom_abline(slope = Diamond_model_y$coefficients[2], intercept = Diamond_model_y$coefficients[1])
```

```{r}
diamond_ma_df %>%
  ggplot()+
  geom_histogram(mapping = aes(x = resid), bins = 10) +
  labs(title = "Residuals of Model A")
```
```{r}
diamond_mu_df %>%
  ggplot()+
  geom_histogram(mapping = aes(x = resid), bins = 10) +
  labs(title = "Residuals of Model U")
```
```{r}
diamond_my_df %>%
  ggplot()+
  geom_histogram(mapping = aes(x = resid), bins = 10) +
  labs(title = "Residuals of Model Y")
```
Model for Carat is Skewed left, Cut and clarity are skewed right.




